// Champions League 26/27 club list for the generalized league engine.
//
// Teams stay empty on purpose: the 36 clubs come out of the league-phase draw, and leagues.js
// sets `seedTeamsFromFeed: true` so scores.js seeds league_teams straight from football-data.org
// (name, TLA code, crest, api_team_id). This file must not restate them — a code assigned here
// that disagreed with the feed's would create a duplicate club.
//
// Squads WERE backfilled after the 2026-08-27 draw (1015 players across 36 clubs), which is what
// makes the player awards — top scorer, goalkeeper of the season — pickable. Two sources, both
// snapshots taken 2026-08-31:
//   * The 14 clubs we already carry in another league (Arsenal, Barça, Inter, …) reuse that
//     league's squad, so the same player reads the same way in both pools.
//   * The other 22 come from the Wikipedia "2026-27 <club> season" / club articles, same method
//     as the La Liga and Serie A files. Only players with a shirt number are kept, which is the
//     line between the registered squad and academy call-ups listed alongside it.
//
// The keys below are the feed's TLA codes; db.js matches squads to clubs on league_teams.code, so
// a key that doesn't match a club the feed seeded is skipped with a log line. There is no live
// squad sync for this league (squadSource: "none"), so this file is the source of truth and
// drifts — the 2026 summer window closes 2026-09-01, after which squads are stable. pos in
// 'GK'|'DF'|'MF'|'FW'.
//
// Consumed by db.js to seed league_teams + league_players tagged league='ucl2627'.

const teams = [];

const squads = {
  AEK: [
    { name: "Alberto Brignoli", pos: "GK" }, { name: "Marios Balamotis", pos: "GK" },
    { name: "Thomas Strakosha", pos: "GK" }, { name: "Charalampos Lykogiannis", pos: "DF" },
    { name: "Christos Alexiou", pos: "DF" }, { name: "Domagoj Vida", pos: "DF" },
    { name: "Filipe Relvas", pos: "DF" }, { name: "Harold Moukoudi", pos: "DF" },
    { name: "Lazaros Rota", pos: "DF" }, { name: "Martin Georgiev", pos: "DF" },
    { name: "Stavros Pilios", pos: "DF" }, { name: "Dereck Kutesa", pos: "MF" },
    { name: "Dimitris Kaloskamis", pos: "MF" }, { name: "Hakim Sahabo", pos: "MF" },
    { name: "Kaan Kairinen", pos: "MF" }, { name: "Kervin Arriaga", pos: "MF" },
    { name: "Lovro Majer", pos: "MF" }, { name: "Mijat Gaćinović", pos: "MF" },
    { name: "Milán Vitális", pos: "MF" }, { name: "Oleksandr Zubkov", pos: "MF" },
    { name: "Petros Mantalos", pos: "MF" }, { name: "Răzvan Marin", pos: "MF" },
    { name: "Aboubakary Koïta", pos: "FW" }, { name: "Barnabás Varga", pos: "FW" },
    { name: "Luka Jović", pos: "FW" }, { name: "Zini", pos: "FW" },
    { name: "Zois Karargyris", pos: "FW" },
  ],
  ARS: [
    { name: "David Raya", pos: "GK" }, { name: "Illan Meslier", pos: "GK" },
    { name: "Kepa Arrizabalaga", pos: "GK" }, { name: "Tommy Setford", pos: "GK" },
    { name: "Ben White", pos: "DF" }, { name: "Cristhian Mosquera", pos: "DF" },
    { name: "Ezri Konsa", pos: "DF" }, { name: "Gabriel Magalhães", pos: "DF" },
    { name: "Jurriën Timber", pos: "DF" }, { name: "Myles Lewis-Skelly", pos: "DF" },
    { name: "Piero Hincapié", pos: "DF" }, { name: "Riccardo Calafiori", pos: "DF" },
    { name: "William Saliba", pos: "DF" }, { name: "Bruno Guimarães", pos: "MF" },
    { name: "Declan Rice", pos: "MF" }, { name: "Eberechi Eze", pos: "MF" },
    { name: "Ethan Nwaneri", pos: "MF" }, { name: "Fábio Vieira", pos: "MF" },
    { name: "Martin Ødegaard", pos: "MF" }, { name: "Martín Zubimendi", pos: "MF" },
    { name: "Max Dowman", pos: "MF" }, { name: "Mikel Merino", pos: "MF" },
    { name: "Bukayo Saka", pos: "FW" }, { name: "Christos Tzolis", pos: "FW" },
    { name: "Gabriel Jesus", pos: "FW" }, { name: "Gabriel Martinelli", pos: "FW" },
    { name: "Kai Havertz", pos: "FW" }, { name: "Noni Madueke", pos: "FW" },
    { name: "Viktor Gyökeres", pos: "FW" },
  ],
  ATL: [
    { name: "Jan Oblak", pos: "GK" }, { name: "Juan Musso", pos: "GK" },
    { name: "Álex Grimaldo", pos: "DF" }, { name: "Daniel Martínez Moreno", pos: "DF" },
    { name: "Dávid Hancko", pos: "DF" }, { name: "Javier Boñar", pos: "DF" },
    { name: "José María Giménez", pos: "DF" }, { name: "Marc Pubill", pos: "DF" },
    { name: "Matteo Ruggeri", pos: "DF" }, { name: "Nahuel Molina", pos: "DF" },
    { name: "Robin Le Normand", pos: "DF" }, { name: "Aleksa Purić", pos: "MF" },
    { name: "Álex Baena", pos: "MF" }, { name: "Giuliano Simeone", pos: "MF" },
    { name: "Iker Luque", pos: "MF" }, { name: "Javier Morcillo Rodrigálvarez", pos: "MF" },
    { name: "Johnny Cardoso", pos: "MF" }, { name: "Koke", pos: "MF" },
    { name: "Lee Kang-in", pos: "MF" }, { name: "Marcos Llorente", pos: "MF" },
    { name: "Miguel Cubo", pos: "MF" }, { name: "Morten Hjulmand", pos: "MF" },
    { name: "Obed Vargas", pos: "MF" }, { name: "Pablo Barrios", pos: "MF" },
    { name: "Rodri Mendoza", pos: "MF" }, { name: "Taufik Seidu", pos: "MF" },
    { name: "Thiago Almada", pos: "MF" }, { name: "Ademola Lookman", pos: "FW" },
    { name: "Alexander Sørloth", pos: "FW" }, { name: "Julián Alvarez", pos: "FW" },
    { name: "Rayane Belaid", pos: "FW" },
  ],
  AVL: [
    { name: "Emiliano Martínez", pos: "GK" }, { name: "James Wright", pos: "GK" },
    { name: "Marco Bizot", pos: "GK" }, { name: "Owen Asemota", pos: "GK" },
    { name: "Zion Suzuki", pos: "GK" }, { name: "Aaron Wan-Bissaka", pos: "DF" },
    { name: "Ian Maatsen", pos: "DF" }, { name: "Matteo Ruggeri", pos: "DF" },
    { name: "Matty Cash", pos: "DF" }, { name: "Modou Kéba Cissé", pos: "DF" },
    { name: "Pau Torres", pos: "DF" }, { name: "Triston Rowe", pos: "DF" },
    { name: "Tyrone Mings", pos: "DF" }, { name: "Victor Lindelöf", pos: "DF" },
    { name: "Aidan Borland", pos: "MF" }, { name: "Amadou Onana", pos: "MF" },
    { name: "Boubacar Kamara", pos: "MF" }, { name: "Emiliano Buendía", pos: "MF" },
    { name: "George Hemmings", pos: "MF" }, { name: "João Gomes", pos: "MF" },
    { name: "Johan Manzambi", pos: "MF" }, { name: "John McGinn", pos: "MF" },
    { name: "Lamare Bogarde", pos: "MF" }, { name: "Leon Goretzka", pos: "MF" },
    { name: "Ross Barkley", pos: "MF" }, { name: "Alejandro Garnacho", pos: "FW" },
    { name: "Alysson", pos: "FW" }, { name: "Bradley Burrowes", pos: "FW" },
    { name: "Brian Madjo", pos: "FW" }, { name: "Leon Bailey", pos: "FW" },
    { name: "Nicolas Jackson", pos: "FW" }, { name: "Ollie Watkins", pos: "FW" },
    { name: "Tammy Abraham", pos: "FW" },
  ],
  BAR: [
    { name: "Joan Garcia", pos: "GK" }, { name: "Marc-André ter Stegen", pos: "GK" },
    { name: "Wojciech Szczęsny", pos: "GK" }, { name: "Alejandro Balde", pos: "DF" },
    { name: "Andreas Christensen", pos: "DF" }, { name: "Eric García", pos: "DF" },
    { name: "Gerard Martín", pos: "DF" }, { name: "Héctor Fort", pos: "DF" },
    { name: "Jules Koundé", pos: "DF" }, { name: "Pau Cubarsí", pos: "DF" },
    { name: "Ronald Araújo", pos: "DF" }, { name: "Dani Olmo", pos: "MF" },
    { name: "Fermín López", pos: "MF" }, { name: "Frenkie de Jong", pos: "MF" },
    { name: "Gavi", pos: "MF" }, { name: "Marc Bernal", pos: "MF" },
    { name: "Marc Casadó", pos: "MF" }, { name: "Pedri", pos: "MF" },
    { name: "Anthony Gordon", pos: "FW" }, { name: "Ferran Torres", pos: "FW" },
    { name: "Jesse Bisiwu", pos: "FW" }, { name: "Karim Adeyemi", pos: "FW" },
    { name: "Lamine Yamal", pos: "FW" }, { name: "Raphinha", pos: "FW" },
    { name: "Roony Bardghji", pos: "FW" },
  ],
  BET: [
    { name: "Álvaro Valles", pos: "GK" }, { name: "Diego Conde", pos: "GK" },
    { name: "Ángel Ortiz", pos: "DF" }, { name: "Diego Llorente", pos: "DF" },
    { name: "Fran García", pos: "DF" }, { name: "Héctor Bellerín", pos: "DF" },
    { name: "Junior Firpo", pos: "DF" }, { name: "Marc Bartra", pos: "DF" },
    { name: "Natan", pos: "DF" }, { name: "Valentín Gómez", pos: "DF" },
    { name: "Álvaro Fidalgo", pos: "MF" }, { name: "Facundo Bernal", pos: "MF" },
    { name: "Giovani Lo Celso", pos: "MF" }, { name: "Isco", pos: "MF" },
    { name: "Marc Roca", pos: "MF" }, { name: "Nelson Deossa", pos: "MF" },
    { name: "Pablo Fornals", pos: "MF" }, { name: "Rodrigo Riquelme", pos: "MF" },
    { name: "Abde Ezzalzouli", pos: "FW" }, { name: "Aitor Ruibal", pos: "FW" },
    { name: "Antony", pos: "FW" }, { name: "Cucho Hernández", pos: "FW" },
    { name: "Pablo García", pos: "FW" },
  ],
  BRU: [
    { name: "Argus Vanden Driessche", pos: "GK" }, { name: "Nordin Jackers", pos: "GK" },
    { name: "Yann Sommer", pos: "GK" }, { name: "Brandon Mechele", pos: "DF" },
    { name: "Hugo Siquet", pos: "DF" }, { name: "Joaquin Seys", pos: "DF" },
    { name: "Joel Ordóñez", pos: "DF" }, { name: "Jorne Spileers", pos: "DF" },
    { name: "Kyriani Sabbe", pos: "DF" }, { name: "Lee Han-beom", pos: "DF" },
    { name: "Matteo Dams", pos: "DF" }, { name: "Alejandro Granados", pos: "MF" },
    { name: "Cheveyo Tsawa", pos: "MF" }, { name: "Félix Lemaréchal", pos: "MF" },
    { name: "Freddie Potts", pos: "MF" }, { name: "Gianluca Okon", pos: "MF" },
    { name: "Hans Vanaken", pos: "MF" }, { name: "Hugo Vetlesen", pos: "MF" },
    { name: "Lynnt Audoor", pos: "MF" }, { name: "Tian Nai Koren", pos: "MF" },
    { name: "Andrej Vasovic", pos: "FW" }, { name: "Carlos Forbs", pos: "FW" },
    { name: "Gustaf Nilsson", pos: "FW" }, { name: "Jan Virgili", pos: "FW" },
    { name: "Mamadou Diakhon", pos: "FW" }, { name: "Nicolò Tresoldi", pos: "FW" },
    { name: "Romeo Vermant", pos: "FW" }, { name: "Wisdom Mike", pos: "FW" },
  ],
  BVB: [
    { name: "Alexander Meyer", pos: "GK" }, { name: "Gregor Kobel", pos: "GK" },
    { name: "Patrick Drewes", pos: "GK" }, { name: "Silas Ostrzinski", pos: "GK" },
    { name: "Daniel Svensson", pos: "DF" }, { name: "Emre Can", pos: "DF" },
    { name: "Filippo Mané", pos: "DF" }, { name: "Joane Gadou", pos: "DF" },
    { name: "Julian Ryerson", pos: "DF" }, { name: "Kauã Prates", pos: "DF" },
    { name: "Luca Reggiani", pos: "DF" }, { name: "Nico Schlotterbeck", pos: "DF" },
    { name: "Ramy Bensebaini", pos: "DF" }, { name: "Waldemar Anton", pos: "DF" },
    { name: "Carney Chukwuemeka", pos: "MF" }, { name: "Enzo dos Santos", pos: "MF" },
    { name: "Felix Nmecha", pos: "MF" }, { name: "Giannis Konstantelias", pos: "MF" },
    { name: "Jobe Bellingham", pos: "MF" }, { name: "Joey Veerman", pos: "MF" },
    { name: "Justin Lerma", pos: "MF" }, { name: "Konstantinos Karetsas", pos: "MF" },
    { name: "Marcel Sabitzer", pos: "MF" }, { name: "Mussa Kaba", pos: "MF" },
    { name: "Fábio Silva", pos: "FW" }, { name: "Mathis Albert", pos: "FW" },
    { name: "Maximilian Beier", pos: "FW" }, { name: "Samuele Inácio", pos: "FW" },
    { name: "Serhou Guirassy", pos: "FW" },
  ],
  COM: [
    { name: "Jean Butez", pos: "GK" }, { name: "Mauro Vigorito", pos: "GK" },
    { name: "Noel Törnqvist", pos: "GK" }, { name: "Álex Valle", pos: "DF" },
    { name: "Andrés Cuenca", pos: "DF" }, { name: "Edoardo Goldaniga", pos: "DF" },
    { name: "Ignace Van Der Brempt", pos: "DF" }, { name: "Ivan Smolčić", pos: "DF" },
    { name: "Jacobo Ramón", pos: "DF" }, { name: "Kaiki Bruno", pos: "DF" },
    { name: "Marc-Oliver Kempf", pos: "DF" }, { name: "Adrian Lahdo", pos: "MF" },
    { name: "Alieu Fadera", pos: "MF" }, { name: "Fabio Rispoli", pos: "MF" },
    { name: "Lucas Da Cunha", pos: "MF" }, { name: "Luis Milla", pos: "MF" },
    { name: "Martin Baturina", pos: "MF" }, { name: "Mattia Liberali", pos: "MF" },
    { name: "Maxence Caqueret", pos: "MF" }, { name: "Máximo Perrone", pos: "MF" },
    { name: "Nico Paz", pos: "MF" }, { name: "Alessandro Gabrielloni", pos: "FW" },
    { name: "Álvaro Morata", pos: "FW" }, { name: "Anastasios Douvikas", pos: "FW" },
    { name: "Assane Diao", pos: "FW" }, { name: "Iván Azón", pos: "FW" },
    { name: "Jayden Addai", pos: "FW" }, { name: "Jesús Rodríguez", pos: "FW" },
    { name: "Nicolas Kühn", pos: "FW" },
  ],
  FCB: [
    { name: "Jannis Bärtl", pos: "GK" }, { name: "Jonas Urbig", pos: "GK" },
    { name: "Manuel Neuer", pos: "GK" }, { name: "Sven Ulreich", pos: "GK" },
    { name: "Alphonso Davies", pos: "DF" }, { name: "Cassiano Kiala", pos: "DF" },
    { name: "Dayot Upamecano", pos: "DF" }, { name: "Filip Pavić", pos: "DF" },
    { name: "Hiroki Itō", pos: "DF" }, { name: "Jonathan Tah", pos: "DF" },
    { name: "Josip Stanišić", pos: "DF" }, { name: "Kim Min-jae", pos: "DF" },
    { name: "Nathaniel Brown", pos: "DF" }, { name: "Sacha Boey", pos: "DF" },
    { name: "Aleksandar Pavlović", pos: "MF" }, { name: "Arijon Ibrahimović", pos: "MF" },
    { name: "Bara Sapoko Ndiaye", pos: "MF" }, { name: "David Santos Daiber", pos: "MF" },
    { name: "Ismael Saibari", pos: "MF" }, { name: "Jamal Musiala", pos: "MF" },
    { name: "Joshua Kimmich", pos: "MF" }, { name: "Konrad Laimer", pos: "MF" },
    { name: "Lennart Karl", pos: "MF" }, { name: "Tom Bischof", pos: "MF" },
    { name: "Bastian Assomo", pos: "FW" }, { name: "Harry Kane", pos: "FW" },
    { name: "Luis Díaz", pos: "FW" }, { name: "Maycon Cardozo", pos: "FW" },
    { name: "Michael Olise", pos: "FW" }, { name: "Serge Gnabry", pos: "FW" },
    { name: "Tim Binder", pos: "FW" },
  ],
  FCP: [
    { name: "Cláudio Ramos", pos: "GK" }, { name: "Diogo Costa", pos: "GK" },
    { name: "João Afonso", pos: "GK" }, { name: "João Costa", pos: "GK" },
    { name: "Alberto Costa", pos: "DF" }, { name: "Dominik Prpić", pos: "DF" },
    { name: "Francisco Moura", pos: "DF" }, { name: "Jakub Kiwior", pos: "DF" },
    { name: "Jan Bednarek", pos: "DF" }, { name: "Martim Fernandes", pos: "DF" },
    { name: "Nehuén Pérez", pos: "DF" }, { name: "Zaidu Sanusi", pos: "DF" },
    { name: "Alan Varela", pos: "MF" }, { name: "Bernardo Lima", pos: "MF" },
    { name: "Eirik Granaas", pos: "MF" }, { name: "Gabri Veiga", pos: "MF" },
    { name: "Hwang In-beom", pos: "MF" }, { name: "Pablo Rosario", pos: "MF" },
    { name: "Seko Fofana", pos: "MF" }, { name: "Tiago Silva", pos: "MF" },
    { name: "Victor Froholdt", pos: "MF" }, { name: "William Gomes", pos: "MF" },
    { name: "André Silva", pos: "FW" }, { name: "Borja Sainz", pos: "FW" },
    { name: "Deniz Gül", pos: "FW" }, { name: "Oskar Pietuszewski", pos: "FW" },
    { name: "Pepê", pos: "FW" }, { name: "Samu Aghehowa", pos: "FW" },
  ],
  FEN: [
    { name: "Ederson", pos: "GK" }, { name: "Mert Günok", pos: "GK" },
    { name: "Tarık Çetin", pos: "GK" }, { name: "Archie Brown", pos: "DF" },
    { name: "Çağlar Söyüncü", pos: "DF" }, { name: "Jayden Oosterwolde", pos: "DF" },
    { name: "Kojo Peprah Oppong", pos: "DF" }, { name: "Levent Mercan", pos: "DF" },
    { name: "Mert Müldür", pos: "DF" }, { name: "Milan Škriniar", pos: "DF" },
    { name: "Nathan Aké", pos: "DF" }, { name: "Nélson Semedo", pos: "DF" },
    { name: "Yiğit Demir", pos: "DF" }, { name: "Adem Yeşilyurt", pos: "MF" },
    { name: "Bartuğ Elmaz", pos: "MF" }, { name: "İrfan Kahveci", pos: "MF" },
    { name: "İsmail Yüksek", pos: "MF" }, { name: "Marco Asensio", pos: "MF" },
    { name: "Mattéo Guendouzi", pos: "MF" }, { name: "Mert Hakan Yandaş", pos: "MF" },
    { name: "N'Golo Kanté", pos: "MF" }, { name: "Talisca", pos: "MF" },
    { name: "Çağrı Balta", pos: "FW" }, { name: "Dorgeles Nene", pos: "FW" },
    { name: "Kerem Aktürkoğlu", pos: "FW" }, { name: "Mason Greenwood", pos: "FW" },
    { name: "Oğuz Aydın", pos: "FW" }, { name: "Romelu Lukaku", pos: "FW" },
    { name: "Vedat Muriqi", pos: "FW" },
  ],
  FEY: [
    { name: "Liam Bossin", pos: "GK" }, { name: "Mannou Berger", pos: "GK" },
    { name: "Tjark Ernst", pos: "GK" }, { name: "Bart Nieuwkoop", pos: "DF" },
    { name: "Gijs Smal", pos: "DF" }, { name: "Givairo Read", pos: "DF" },
    { name: "Javi López", pos: "DF" }, { name: "Jerry St. Juste", pos: "DF" },
    { name: "Jordan Bos", pos: "DF" }, { name: "Jordan Lotomba", pos: "DF" },
    { name: "Mats Deijl", pos: "DF" }, { name: "Mika Mármol", pos: "DF" },
    { name: "Thomas Beelen", pos: "DF" }, { name: "Tsuyoshi Watanabe", pos: "DF" },
    { name: "Charles Vanhoutte", pos: "MF" }, { name: "Gjivai Zechiël", pos: "MF" },
    { name: "Jakub Moder", pos: "MF" }, { name: "Luciano Valente", pos: "MF" },
    { name: "Luka Ivanušec", pos: "MF" }, { name: "Oussama Targhalline", pos: "MF" },
    { name: "Sem Steijn", pos: "MF" }, { name: "Thijs Kraaijeveld", pos: "MF" },
    { name: "Tobias van den Elshout", pos: "MF" }, { name: "Anis Hadj Moussa", pos: "FW" },
    { name: "Ayase Ueda", pos: "FW" }, { name: "Casper Tengstedt", pos: "FW" },
    { name: "Gaoussou Diarra", pos: "FW" }, { name: "Gonçalo Borges", pos: "FW" },
    { name: "Jivayno Zinhagel", pos: "FW" }, { name: "Nacho Ferri", pos: "FW" },
    { name: "Shaqueel van Persie", pos: "FW" }, { name: "Tijme Wessels", pos: "FW" },
  ],
  FK: [
    { name: "Isak Sjong", pos: "GK" }, { name: "Julian Faye Lund", pos: "GK" },
    { name: "Magnus Brøndbo", pos: "GK" }, { name: "Nikita Haikin", pos: "GK" },
    { name: "Fredrik André Bjørkan", pos: "DF" }, { name: "Haitam Aleesami", pos: "DF" },
    { name: "Isak Dybvik Määttä", pos: "DF" }, { name: "Jostein Gundersen", pos: "DF" },
    { name: "Odin Bjørtuft", pos: "DF" }, { name: "Villads Nielsen", pos: "DF" },
    { name: "Anders Klynge", pos: "MF" }, { name: "Fredrik Sjøvold", pos: "MF" },
    { name: "Håkon Evjen", pos: "MF" }, { name: "Magnus Bech Riisnæs", pos: "MF" },
    { name: "Patrick Berg", pos: "MF" }, { name: "Sondre Auklend", pos: "MF" },
    { name: "Sondre Brunstad Fet", pos: "MF" }, { name: "Ulrik Saltnes", pos: "MF" },
    { name: "Andreas Helmersen", pos: "FW" }, { name: "August Mikkelsen", pos: "FW" },
    { name: "Daniel Bassi", pos: "FW" }, { name: "Gift Sunday", pos: "FW" },
    { name: "Hindrin Najah Chooly", pos: "FW" }, { name: "Jens Petter Hauge", pos: "FW" },
    { name: "Kasper Høgh", pos: "FW" }, { name: "Mikkel Bro Hansen", pos: "FW" },
    { name: "Ola Brynhildsen", pos: "FW" }, { name: "Ole Didrik Blomberg", pos: "FW" },
  ],
  GAL: [
    { name: "Arda Yılmaz", pos: "GK" }, { name: "Enes Büyük", pos: "GK" },
    { name: "Günay Güvenç", pos: "GK" }, { name: "Jankat Yılmaz", pos: "GK" },
    { name: "Uğurcan Çakır", pos: "GK" }, { name: "Abdülkerim Bardakcı", pos: "DF" },
    { name: "Arda Ünyay", pos: "DF" }, { name: "Davinson Sánchez", pos: "DF" },
    { name: "Eren Elmalı", pos: "DF" }, { name: "Ismail Jakobs", pos: "DF" },
    { name: "Kaan Ayhan", pos: "DF" }, { name: "Kazımcan Karataş", pos: "DF" },
    { name: "Roland Sallai", pos: "DF" }, { name: "Victor Nelsson", pos: "DF" },
    { name: "Wilfried Singo", pos: "DF" }, { name: "Aleksey Batrakov", pos: "MF" },
    { name: "Berat Luş", pos: "MF" }, { name: "Eyüp Aydın", pos: "MF" },
    { name: "Gabriel Sara", pos: "MF" }, { name: "İlkay Gündoğan", pos: "MF" },
    { name: "Lesley Ugochukwu", pos: "MF" }, { name: "Lucas Torreira", pos: "MF" },
    { name: "Mario Lemina", pos: "MF" }, { name: "Renato Nhaga", pos: "MF" },
    { name: "Ada Yüzgeç", pos: "FW" }, { name: "Barış Yılmaz", pos: "FW" },
    { name: "Leroy Sané", pos: "FW" }, { name: "Rafael Leão", pos: "FW" },
    { name: "Victor Osimhen", pos: "FW" }, { name: "Yunus Akgün", pos: "FW" },
  ],
  INT: [
    { name: "Ivan Provedel", pos: "GK" }, { name: "Josep Martínez", pos: "GK" },
    { name: "Raffaele Di Gennaro", pos: "GK" }, { name: "Alessandro Bastoni", pos: "DF" },
    { name: "Benjamin Pavard", pos: "DF" }, { name: "Carlos Augusto", pos: "DF" },
    { name: "Federico Dimarco", pos: "DF" }, { name: "John Stones", pos: "DF" },
    { name: "Manuel Akanji", pos: "DF" }, { name: "Yann Bisseck", pos: "DF" },
    { name: "Aleksandar Stanković", pos: "MF" }, { name: "Andy Diouf", pos: "MF" },
    { name: "Davide Frattesi", pos: "MF" }, { name: "Hakan Çalhanoğlu", pos: "MF" },
    { name: "Henrikh Mkhitaryan", pos: "MF" }, { name: "Kristjan Asllani", pos: "MF" },
    { name: "Luis Henrique", pos: "MF" }, { name: "Nicolò Barella", pos: "MF" },
    { name: "Petar Sučić", pos: "MF" }, { name: "Piotr Zieliński", pos: "MF" },
    { name: "Yanis Massolin", pos: "MF" }, { name: "Ange-Yoan Bonny", pos: "FW" },
    { name: "Lautaro Martínez", pos: "FW" }, { name: "Marcus Thuram", pos: "FW" },
    { name: "Pio Esposito", pos: "FW" },
  ],
  LIL: [
    { name: "Arnaud Bodart", pos: "GK" }, { name: "Berke Özer", pos: "GK" },
    { name: "Alexsandro", pos: "DF" }, { name: "Calvin Verdonk", pos: "DF" },
    { name: "Isaac Cossier", pos: "DF" }, { name: "Loun Srdanovic", pos: "DF" },
    { name: "Nathan Ngoy", pos: "DF" }, { name: "Ousmane Touré", pos: "DF" },
    { name: "Romain Perraud", pos: "DF" }, { name: "Tanguy Nianzou", pos: "DF" },
    { name: "Tiago Santos", pos: "DF" }, { name: "Ayyoub Bouaddi", pos: "MF" },
    { name: "Benjamin André", pos: "MF" }, { name: "Hákon Haraldsson", pos: "MF" },
    { name: "Ngal'ayel Mukau", pos: "MF" }, { name: "Başar Önal", pos: "FW" },
    { name: "Ethan Mbappé", pos: "FW" }, { name: "Félix Correia", pos: "FW" },
    { name: "Gaëtan Perrin", pos: "FW" }, { name: "Hamza Igamane", pos: "FW" },
    { name: "Marius Broholm", pos: "FW" }, { name: "Matias Fernandez-Pardo", pos: "FW" },
    { name: "Noah Edjouma", pos: "FW" }, { name: "Olivier Giroud", pos: "FW" },
    { name: "Osame Sahraoui", pos: "FW" }, { name: "Soriba Diaoune", pos: "FW" },
  ],
  LIN: [
    { name: "Fabian Schillinger", pos: "GK" }, { name: "Lukas Jungwirth", pos: "GK" },
    { name: "Tobias Schützenauer", pos: "GK" }, { name: "Andrés Andrade", pos: "DF" },
    { name: "Cheikne Kébé", pos: "DF" }, { name: "George Bello", pos: "DF" },
    { name: "João Tornich", pos: "DF" }, { name: "Kasper Jørgensen", pos: "DF" },
    { name: "Manoël Verhaeghe", pos: "DF" }, { name: "Melayro Bogarde", pos: "DF" },
    { name: "Miguel Freckleton", pos: "DF" }, { name: "Xavier Mbuyamba", pos: "DF" },
    { name: "Yvan Dibango", pos: "DF" }, { name: "Alessandro Schöpf", pos: "MF" },
    { name: "Art Smakaj", pos: "MF" }, { name: "Florian Flecker", pos: "MF" },
    { name: "Kryštof Daněk", pos: "MF" }, { name: "Robert Ljubičić", pos: "MF" },
    { name: "Sascha Horvath", pos: "MF" }, { name: "Christoph Lang", pos: "FW" },
    { name: "Moses Usor", pos: "FW" }, { name: "Ramiz Harakaté", pos: "FW" },
    { name: "Samuel Adeniran", pos: "FW" },
  ],
  LIV: [
    { name: "Alisson Becker", pos: "GK" }, { name: "Freddie Woodman", pos: "GK" },
    { name: "Harvey Davies", pos: "GK" }, { name: "Vítezslav Jaros", pos: "GK" },
    { name: "Conor Bradley", pos: "DF" }, { name: "Giovanni Leoni", pos: "DF" },
    { name: "Jeremie Frimpong", pos: "DF" }, { name: "Jérémy Jacquet", pos: "DF" },
    { name: "Joe Gomez", pos: "DF" }, { name: "Kostas Tsimikas", pos: "DF" },
    { name: "Milos Kerkez", pos: "DF" }, { name: "Natalia Ramos", pos: "DF" },
    { name: "Ronald Araujo", pos: "DF" }, { name: "Virgil van Dijk", pos: "DF" },
    { name: "Alexis Mac Allister", pos: "MF" }, { name: "Dominik Szoboszlai", pos: "MF" },
    { name: "Florian Wirtz", pos: "MF" }, { name: "Harvey Elliott", pos: "MF" },
    { name: "James McConnell", pos: "MF" }, { name: "Ryan Gravenberch", pos: "MF" },
    { name: "Stefan Bajcetic", pos: "MF" }, { name: "Trey Nyoni", pos: "MF" },
    { name: "Wataru Endo", pos: "MF" }, { name: "Alexander Isak", pos: "FW" },
    { name: "Cody Gakpo", pos: "FW" }, { name: "Federico Chiesa", pos: "FW" },
    { name: "Hugo Ekitiké", pos: "FW" }, { name: "Lewis Koumas", pos: "FW" },
    { name: "Rio Ngumoha", pos: "FW" }, { name: "Víctor Muñoz", pos: "FW" },
  ],
  MCI: [
    { name: "Gerónimo Rulli", pos: "GK" }, { name: "Gianluigi Donnarumma", pos: "GK" },
    { name: "Marcus Bettinelli", pos: "GK" }, { name: "Abdukodir Khusanov", pos: "DF" },
    { name: "Finley Burns", pos: "DF" }, { name: "Josh Wilson-Esbrand", pos: "DF" },
    { name: "Josko Gvardiol", pos: "DF" }, { name: "Kaden Braithwaite", pos: "DF" },
    { name: "Marc Guéhi", pos: "DF" }, { name: "Nico O'Reilly", pos: "DF" },
    { name: "Rayan Aït-Nouri", pos: "DF" }, { name: "Rico Lewis", pos: "DF" },
    { name: "Rúben Dias", pos: "DF" }, { name: "Vitor Reis", pos: "DF" },
    { name: "Ayyoub Bouaddi", pos: "MF" }, { name: "Claudio Echeverri", pos: "MF" },
    { name: "Elliot Anderson", pos: "MF" }, { name: "Jack Grealish", pos: "MF" },
    { name: "Mateo Kovacic", pos: "MF" }, { name: "Matheus Nunes", pos: "MF" },
    { name: "Phil Foden", pos: "MF" }, { name: "Rayan Cherki", pos: "MF" },
    { name: "Antoine Semenyo", pos: "FW" }, { name: "Erling Haaland", pos: "FW" },
    { name: "Jérémy Doku", pos: "FW" }, { name: "Jeremy Monga", pos: "FW" },
    { name: "Ryan McAidoo", pos: "FW" },
  ],
  MUN: [
    { name: "André Onana", pos: "GK" }, { name: "Dermot Mee", pos: "GK" },
    { name: "Karl Darlow", pos: "GK" }, { name: "Senne Lammens", pos: "GK" },
    { name: "Tom Heaton", pos: "GK" }, { name: "Ayden Heaven", pos: "DF" },
    { name: "Diogo Dalot", pos: "DF" }, { name: "Harry Amass", pos: "DF" },
    { name: "Harry Maguire", pos: "DF" }, { name: "Leny Yoro", pos: "DF" },
    { name: "Lisandro Martínez", pos: "DF" }, { name: "Luke Shaw", pos: "DF" },
    { name: "Matthijs de Ligt", pos: "DF" }, { name: "Noussair Mazraoui", pos: "DF" },
    { name: "Patrick Dorgu", pos: "DF" }, { name: "Andrey Santos", pos: "MF" },
    { name: "Bruno Fernandes", pos: "MF" }, { name: "Carlos Baleba", pos: "MF" },
    { name: "Jack Fletcher", pos: "MF" }, { name: "Kobbie Mainoo", pos: "MF" },
    { name: "Manuel Ugarte", pos: "MF" }, { name: "Mason Mount", pos: "MF" },
    { name: "Toby Collyer", pos: "MF" }, { name: "Tyler Fletcher", pos: "MF" },
    { name: "Youri Tielemans", pos: "MF" }, { name: "Amad Diallo", pos: "FW" },
    { name: "Benjamin Sesko", pos: "FW" }, { name: "Bryan Mbeumo", pos: "FW" },
    { name: "Joshua Zirkzee", pos: "FW" }, { name: "Marcus Rashford", pos: "FW" },
    { name: "Matheus Cunha", pos: "FW" }, { name: "Shea Lacey", pos: "FW" },
  ],
  NAP: [
    { name: "Alex Meret", pos: "GK" }, { name: "Nikita Contini", pos: "GK" },
    { name: "Vanja Milinković-Savić", pos: "GK" }, { name: "Alessandro Buongiorno", pos: "DF" },
    { name: "Amir Rrahmani", pos: "DF" }, { name: "Giovanni Di Lorenzo", pos: "DF" },
    { name: "Leonardo Spinazzola", pos: "DF" }, { name: "Mathías Olivera", pos: "DF" },
    { name: "Miguel Gutiérrez", pos: "DF" }, { name: "Pasquale Mazzocchi", pos: "DF" },
    { name: "Sam Beukema", pos: "DF" }, { name: "Antonio Vergara", pos: "MF" },
    { name: "Billy Gilmour", pos: "MF" }, { name: "Frank Anguissa", pos: "MF" },
    { name: "Kevin De Bruyne", pos: "MF" }, { name: "Scott McTominay", pos: "MF" },
    { name: "Stanislav Lobotka", pos: "MF" }, { name: "Alisson Santos", pos: "FW" },
    { name: "David Neres", pos: "FW" }, { name: "Giovane", pos: "FW" },
    { name: "Matteo Politano", pos: "FW" }, { name: "Rasmus Højlund", pos: "FW" },
    { name: "Romelu Lukaku", pos: "FW" },
  ],
  PSG: [
    { name: "Alessandro Longoni", pos: "GK" }, { name: "Lucas Chevalier", pos: "GK" },
    { name: "Matvey Safonov", pos: "GK" }, { name: "Achraf Hakimi", pos: "DF" },
    { name: "Illia Zabarnyi", pos: "DF" }, { name: "Lucas Beraldo", pos: "DF" },
    { name: "Lucas Digne", pos: "DF" }, { name: "Lucas Hernandez", pos: "DF" },
    { name: "Marquinhos", pos: "DF" }, { name: "Nuno Mendes", pos: "DF" },
    { name: "Willian Pacho", pos: "DF" }, { name: "Dro Fernández", pos: "MF" },
    { name: "Fabián Ruiz", pos: "MF" }, { name: "João Neves", pos: "MF" },
    { name: "Maghnes Akliouche", pos: "MF" }, { name: "Senny Mayulu", pos: "MF" },
    { name: "Vitinha", pos: "MF" }, { name: "Warren Zaïre-Emery", pos: "MF" },
    { name: "Bradley Barcola", pos: "FW" }, { name: "Désiré Doué", pos: "FW" },
    { name: "Ferran Torres", pos: "FW" }, { name: "Ibrahim Mbaye", pos: "FW" },
    { name: "Khvicha Kvaratskhelia", pos: "FW" }, { name: "Mika Godts", pos: "FW" },
    { name: "Ousmane Dembélé", pos: "FW" }, { name: "Quentin Ndjantou", pos: "FW" },
  ],
  PSV: [
    { name: "Matěj Kovář", pos: "GK" }, { name: "Nick Olij", pos: "GK" },
    { name: "Tijn Smolenaars", pos: "GK" }, { name: "Adamo Nagalo", pos: "DF" },
    { name: "Armando Obispo", pos: "DF" }, { name: "Fabian Merién", pos: "DF" },
    { name: "Kiliann Sildillia", pos: "DF" }, { name: "Lutsharel Geertruida", pos: "DF" },
    { name: "Mauro Júnior", pos: "DF" }, { name: "Ryan Flamingo", pos: "DF" },
    { name: "Sergiño Dest", pos: "DF" }, { name: "Yarek Gasiorowski", pos: "DF" },
    { name: "Filip Kostić", pos: "MF" }, { name: "Guus Til", pos: "MF" },
    { name: "Isaac Babadi", pos: "MF" }, { name: "Ivan Perišić", pos: "MF" },
    { name: "Jerdy Schouten", pos: "MF" }, { name: "Joël van den Berg", pos: "MF" },
    { name: "Kodai Sano", pos: "MF" }, { name: "Noah Fernandez", pos: "MF" },
    { name: "Paul Wanner", pos: "MF" }, { name: "Sven Mijnans", pos: "MF" },
    { name: "Alassane Pléa", pos: "FW" }, { name: "Couhaib Driouech", pos: "FW" },
    { name: "Dennis Man", pos: "FW" }, { name: "Esmir Bajraktarević", pos: "FW" },
    { name: "Ricardo Pepi", pos: "FW" }, { name: "Ruben van Bommel", pos: "FW" },
  ],
  RBL: [
    { name: "Leopold Zingerle", pos: "GK" }, { name: "Maarten Vandevoordt", pos: "GK" },
    { name: "Ørjan Nyland", pos: "GK" }, { name: "Abdoul Koné", pos: "DF" },
    { name: "Benjamin Henrichs", pos: "DF" }, { name: "Castello Lukeba", pos: "DF" },
    { name: "David Raum", pos: "DF" }, { name: "El Chadaille Bitshiabu", pos: "DF" },
    { name: "Joyeux Masanka Bungi", pos: "DF" }, { name: "Lukas Klostermann", pos: "DF" },
    { name: "Max Finkgräfe", pos: "DF" }, { name: "Maxime Estève", pos: "DF" },
    { name: "Ridle Baku", pos: "DF" }, { name: "Willi Orbán", pos: "DF" },
    { name: "Andrija Maksimović", pos: "MF" }, { name: "Arthur Vermeeren", pos: "MF" },
    { name: "Assan Ouédraogo", pos: "MF" }, { name: "Benno Kaltefleiter", pos: "MF" },
    { name: "Brajan Gruda", pos: "MF" }, { name: "Christoph Baumgartner", pos: "MF" },
    { name: "Ezechiel Banzuzi", pos: "MF" }, { name: "Nicolas Seiwald", pos: "MF" },
    { name: "Rocco Reitz", pos: "MF" }, { name: "Viggo Gebel", pos: "MF" },
    { name: "Antonio Nusa", pos: "FW" }, { name: "Ayodele Thomas", pos: "FW" },
    { name: "Christopher Nkunku", pos: "FW" }, { name: "Conrad Harder", pos: "FW" },
    { name: "Johan Bakayoko", pos: "FW" }, { name: "Rômulo", pos: "FW" },
    { name: "Samba Konaté", pos: "FW" }, { name: "Suleman Sani", pos: "FW" },
    { name: "Tidiam Gomis", pos: "FW" },
  ],
  RCL: [
    { name: "Ilan Jourdren", pos: "GK" }, { name: "Mathieu Gorgelin", pos: "GK" },
    { name: "Régis Gurtner", pos: "GK" }, { name: "Robin Risser", pos: "GK" },
    { name: "Ismaëlo Ganiou", pos: "DF" }, { name: "Jhoanner Chávez", pos: "DF" },
    { name: "Jonathan Gradit", pos: "DF" }, { name: "Kyllian Antonio", pos: "DF" },
    { name: "Maik Nawrocki", pos: "DF" }, { name: "Matthieu Udol", pos: "DF" },
    { name: "Nidal Čelik", pos: "DF" }, { name: "Ruben Aguilar", pos: "DF" },
    { name: "Samson Baidoo", pos: "DF" }, { name: "Saud Abdulhamid", pos: "DF" },
    { name: "Souleymane Sagnan", pos: "DF" }, { name: "Alpha Diallo", pos: "MF" },
    { name: "Amadou Haidara", pos: "MF" }, { name: "Andrija Bulatović", pos: "MF" },
    { name: "Florian Thauvin", pos: "MF" }, { name: "Mezian Mesloub", pos: "MF" },
    { name: "Michaël Cuisance", pos: "MF" }, { name: "Michał Skóraś", pos: "MF" },
    { name: "Yacine Titraoui", pos: "MF" }, { name: "Abdallah Sima", pos: "FW" },
    { name: "Florian Sotoca", pos: "FW" }, { name: "Franjo Ivanović", pos: "FW" },
    { name: "Odsonne Édouard", pos: "FW" }, { name: "Rayan Fofana", pos: "FW" },
    { name: "Thorgan Hazard", pos: "FW" },
  ],
  RMA: [
    { name: "Andriy Lunin", pos: "GK" }, { name: "Thibaut Courtois", pos: "GK" },
    { name: "Álvaro Carreras", pos: "DF" }, { name: "Antonio Rüdiger", pos: "DF" },
    { name: "Dean Huijsen", pos: "DF" }, { name: "Denzel Dumfries", pos: "DF" },
    { name: "Éder Militão", pos: "DF" }, { name: "Ferland Mendy", pos: "DF" },
    { name: "Ibrahima Konaté", pos: "DF" }, { name: "Marc Cucurella", pos: "DF" },
    { name: "Raúl Asencio", pos: "DF" }, { name: "Trent Alexander-Arnold", pos: "DF" },
    { name: "Arda Güler", pos: "MF" }, { name: "Aurélien Tchouaméni", pos: "MF" },
    { name: "Bernardo Silva", pos: "MF" }, { name: "Eduardo Camavinga", pos: "MF" },
    { name: "Federico Valverde", pos: "MF" }, { name: "Jude Bellingham", pos: "MF" },
    { name: "Brahim Díaz", pos: "FW" }, { name: "Carlos Espí", pos: "FW" },
    { name: "Endrick", pos: "FW" }, { name: "Franco Mastantuono", pos: "FW" },
    { name: "Gonzalo García", pos: "FW" }, { name: "Kylian Mbappé", pos: "FW" },
    { name: "Rodrygo", pos: "FW" }, { name: "Vinícius Júnior", pos: "FW" },
  ],
  ROM: [
    { name: "Giorgio De Marzi", pos: "GK" }, { name: "Mile Svilar", pos: "GK" },
    { name: "Pierluigi Gollini", pos: "GK" }, { name: "Angeliño", pos: "DF" },
    { name: "Daniele Ghilardi", pos: "DF" }, { name: "Devyne Rensch", pos: "DF" },
    { name: "Evan Ndicka", pos: "DF" }, { name: "Filippo Reale", pos: "DF" },
    { name: "Gianluca Mancini", pos: "DF" }, { name: "Jan Ziółkowski", pos: "DF" },
    { name: "Konstantinos Koulierakis", pos: "DF" }, { name: "Mario Hermoso", pos: "DF" },
    { name: "Mattia Mannini", pos: "DF" }, { name: "Wesley França", pos: "DF" },
    { name: "Bryan Cristante", pos: "MF" }, { name: "Manu Koné", pos: "MF" },
    { name: "Neil El Aynaoui", pos: "MF" }, { name: "Niccolò Pisilli", pos: "MF" },
    { name: "Donyell Malen", pos: "FW" }, { name: "Luigi Cherubini", pos: "FW" },
    { name: "Matías Soulé", pos: "FW" }, { name: "Paulo Dybala", pos: "FW" },
    { name: "Robinio Vaz", pos: "FW" }, { name: "Santiago Castro", pos: "FW" },
  ],
  SAB: [
    { name: "Amin Ramazanov", pos: "GK" }, { name: "Ravan Mirzammadov", pos: "GK" },
    { name: "Stas Pokatilov", pos: "GK" }, { name: "Aden McCarthy", pos: "DF" },
    { name: "Akim Zedadka", pos: "DF" }, { name: "Erivaldo Almeida", pos: "DF" },
    { name: "Godfred Boakye", pos: "DF" }, { name: "Japhet Dungus", pos: "DF" },
    { name: "Rahman Dashdamirov", pos: "DF" }, { name: "Steve Solvet", pos: "DF" },
    { name: "Tellur Mutallimov", pos: "DF" }, { name: "Tymoteusz Puchacz", pos: "DF" },
    { name: "Abdulakh Khaybulayev", pos: "MF" }, { name: "Aleksey Isayev", pos: "MF" },
    { name: "Ivan Lepinjica", pos: "MF" }, { name: "Jafar Mukhtarov", pos: "MF" },
    { name: "Kaheem Parris", pos: "MF" }, { name: "Khayal Aliyev", pos: "MF" },
    { name: "Rauf Rustamli", pos: "MF" }, { name: "Rodrigo Fernandes", pos: "MF" },
    { name: "Shahin Ibrahimov", pos: "MF" }, { name: "Umarali Rakhmonaliev", pos: "MF" },
    { name: "Veljko Simić", pos: "MF" }, { name: "Zinédine Ould Khaled", pos: "MF" },
    { name: "Christian Nwachukwu", pos: "FW" }, { name: "Joy-Lance Mickels", pos: "FW" },
    { name: "Orphé Mbina", pos: "FW" }, { name: "Xander Severina", pos: "FW" },
    { name: "Younes Lachaab", pos: "FW" },
  ],
  SBA: [
    { name: "Aleksandar Popović", pos: "GK" }, { name: "Dominik Takáč", pos: "GK" },
    { name: "Matúš Macík", pos: "GK" }, { name: "César Blackman", pos: "DF" },
    { name: "Jurij Medveděv", pos: "DF" }, { name: "Kenan Bajrić", pos: "DF" },
    { name: "Kevin Wimmer", pos: "DF" }, { name: "Samuel Kozlovský", pos: "DF" },
    { name: "Sandro Cruz", pos: "DF" }, { name: "Svetozar Marković", pos: "DF" },
    { name: "Alen Mustafić", pos: "MF" }, { name: "Artur Gajdoš", pos: "MF" },
    { name: "Cristian Martínez", pos: "MF" }, { name: "Daiki Matsuoka", pos: "MF" },
    { name: "Danylo Ihnatenko", pos: "MF" }, { name: "Peter Pokorný", pos: "MF" },
    { name: "Rahim Ibrahim", pos: "MF" }, { name: "Tigran Barseghyan", pos: "MF" },
    { name: "Adam Griger", pos: "FW" }, { name: "Alasana Yirajang", pos: "FW" },
    { name: "Alexej Maroš", pos: "FW" }, { name: "Andraž Šporar", pos: "FW" },
    { name: "Kelvin Ofori", pos: "FW" }, { name: "Manasse Kianga", pos: "FW" },
    { name: "Matúš Tomáško", pos: "FW" }, { name: "Mykola Kukharevych", pos: "FW" },
    { name: "Nino Marcelli", pos: "FW" }, { name: "Roman Čerepkai", pos: "FW" },
    { name: "Suleiman Camara", pos: "FW" },
  ],
  SHD: [
    { name: "Denys Tvardovskyi", pos: "GK" }, { name: "Dmytro Riznyk", pos: "GK" },
    { name: "Kiril Fesyun", pos: "GK" }, { name: "Alaa Ghram", pos: "DF" },
    { name: "Irakli Azarovi", pos: "DF" }, { name: "Marlon Santos", pos: "DF" },
    { name: "Mykola Matviyenko", pos: "DF" }, { name: "Oleksandr Karavayev", pos: "DF" },
    { name: "Pedro Henrique", pos: "DF" }, { name: "Valeriy Bondar", pos: "DF" },
    { name: "Vinicius Tobias", pos: "DF" }, { name: "Dmytro Kryskiv", pos: "MF" },
    { name: "Gleiker Mendoza", pos: "MF" }, { name: "Isaque", pos: "MF" },
    { name: "Lucas Ferreira", pos: "MF" }, { name: "Marlon Gomes", pos: "MF" },
    { name: "Newerton", pos: "MF" }, { name: "Oleh Ocheretko", pos: "MF" },
    { name: "Pedrinho", pos: "MF" }, { name: "Viktor Tsukanov", pos: "MF" },
    { name: "Yehor Nazaryna", pos: "MF" }, { name: "Alisson", pos: "FW" },
    { name: "Bruninho", pos: "FW" }, { name: "Eguinaldo", pos: "FW" },
    { name: "Kauã Elias", pos: "FW" }, { name: "Lassina Traoré", pos: "FW" },
    { name: "Luca Meirelles", pos: "FW" }, { name: "Prosper Obah", pos: "FW" },
    { name: "Ryan Roberto", pos: "FW" },
  ],
  SLP: [
    { name: "Jakub Markovič", pos: "GK" }, { name: "Jindřich Staněk", pos: "GK" },
    { name: "Nazar Domchak", pos: "GK" }, { name: "Ondřej Kolář", pos: "GK" },
    { name: "Ange N'Guessan", pos: "DF" }, { name: "David Jurásek", pos: "DF" },
    { name: "David Zima", pos: "DF" }, { name: "Denis Halinský", pos: "DF" },
    { name: "Eliáš Piták", pos: "DF" }, { name: "Igoh Ogbu", pos: "DF" },
    { name: "Mikuláš Konečný", pos: "DF" }, { name: "Sahmkou Camara", pos: "DF" },
    { name: "Samuel Isife", pos: "DF" }, { name: "Štěpán Chaloupek", pos: "DF" },
    { name: "Tomáš Holeš", pos: "DF" }, { name: "Tomáš Vlček", pos: "DF" },
    { name: "Danijel Šturm", pos: "MF" }, { name: "David Moses", pos: "MF" },
    { name: "Lukáš Provod", pos: "MF" }, { name: "Michal Sadílek", pos: "MF" },
    { name: "Mubarak Suleiman", pos: "MF" }, { name: "Oskar Kubiak", pos: "MF" },
    { name: "Pavel Kačor", pos: "MF" }, { name: "Toumani Diakité", pos: "MF" },
    { name: "Wiktor Nowak", pos: "MF" }, { name: "Youssoupha Sanyang", pos: "MF" },
    { name: "Adonija Ouanda", pos: "FW" }, { name: "Emmanuel Ayaosi", pos: "FW" },
    { name: "Ivan Schranz", pos: "FW" }, { name: "Mojmír Chytil", pos: "FW" },
    { name: "Tomáš Chorý", pos: "FW" },
  ],
  SPO: [
    { name: "Diego Callai", pos: "GK" }, { name: "Francisco Silva", pos: "GK" },
    { name: "João Virgínia", pos: "GK" }, { name: "Rui Silva", pos: "GK" },
    { name: "Eduardo Quaresma", pos: "DF" }, { name: "Georgios Vagiannidis", pos: "DF" },
    { name: "Gonçalo Inácio", pos: "DF" }, { name: "Iván Fresneda", pos: "DF" },
    { name: "Nuno Santos", pos: "DF" }, { name: "Ousmane Diomande", pos: "DF" },
    { name: "Zeno Debast", pos: "DF" }, { name: "Daniel Bragança", pos: "MF" },
    { name: "Flávio Gonçalves", pos: "MF" }, { name: "Giorgi Kochorashvili", pos: "MF" },
    { name: "Issa Doumbia", pos: "MF" }, { name: "João Simões", pos: "MF" },
    { name: "Koba Koindredi", pos: "MF" }, { name: "Pedro Gonçalves", pos: "MF" },
    { name: "Pedro Lima", pos: "MF" }, { name: "Rodrigo Zalazar", pos: "MF" },
    { name: "Sergi Altimira", pos: "MF" }, { name: "Silas Andersen", pos: "MF" },
    { name: "Fotis Ioannidis", pos: "FW" }, { name: "Geny Catamo", pos: "FW" },
    { name: "Jesse Derry", pos: "FW" }, { name: "Luis Guilherme", pos: "FW" },
    { name: "Luis Suárez", pos: "FW" }, { name: "Maximiliano Araújo", pos: "FW" },
    { name: "Rafael Nel", pos: "FW" },
  ],
  VFB: [
    { name: "Dennis Seimen", pos: "GK" }, { name: "Fabian Bredlow", pos: "GK" },
    { name: "Marius Funk", pos: "GK" }, { name: "Ameen Al-Dakhil", pos: "DF" },
    { name: "Dan-Axel Zagadou", pos: "DF" }, { name: "Finn Jeltsch", pos: "DF" },
    { name: "Jeff Chabot", pos: "DF" }, { name: "Josha Vagnoman", pos: "DF" },
    { name: "Leonidas Stergiou", pos: "DF" }, { name: "Lorenz Assignon", pos: "DF" },
    { name: "Luca Jaquez", pos: "DF" }, { name: "Maximilian Mittelstädt", pos: "DF" },
    { name: "Ramon Hendriks", pos: "DF" }, { name: "Angelo Stiller", pos: "MF" },
    { name: "Atakan Karazor", pos: "MF" }, { name: "Bilal El Khannouss", pos: "MF" },
    { name: "Chema Andrés", pos: "MF" }, { name: "Chris Führich", pos: "MF" },
    { name: "Grischa Prömel", pos: "MF" }, { name: "Mirza Ćatović", pos: "MF" },
    { name: "Nikolas Nartey", pos: "MF" }, { name: "Yanik Spalt", pos: "MF" },
    { name: "Badredine Bouanani", pos: "FW" }, { name: "Deniz Undav", pos: "FW" },
    { name: "Dženan Pejčinović", pos: "FW" }, { name: "Ermedin Demirović", pos: "FW" },
    { name: "Jamie Leweling", pos: "FW" }, { name: "Jeremy Arévalo", pos: "FW" },
    { name: "Lazar Jovanović", pos: "FW" }, { name: "Leo Sauer", pos: "FW" },
    { name: "Tiago Tomás", pos: "FW" }, { name: "Tim van der Leij", pos: "FW" },
  ],
  VIK: [
    { name: "Arild Østbø", pos: "GK" }, { name: "Erlend Jacobsen", pos: "GK" },
    { name: "Ľubomír Belko", pos: "GK" }, { name: "Anders Bærtelsen", pos: "DF" },
    { name: "Gianni Stensness", pos: "DF" }, { name: "Henrik Falchener", pos: "DF" },
    { name: "Henrik Heggheim", pos: "DF" }, { name: "Herman Haugen", pos: "DF" },
    { name: "Jesper Daland", pos: "DF" }, { name: "Kristoffer Haugen", pos: "DF" },
    { name: "Martin Ove Roseth", pos: "DF" }, { name: "Sondre Bjørshol", pos: "DF" },
    { name: "Vetle Auklend", pos: "DF" }, { name: "Viljar Vevatne", pos: "DF" },
    { name: "Jakob Segadal Hansen", pos: "MF" }, { name: "Joe Bell", pos: "MF" },
    { name: "Kristoffer Askildsen", pos: "MF" }, { name: "Ola Visted", pos: "MF" },
    { name: "Ruben Alte", pos: "MF" }, { name: "Simen Kvia-Egeskog", pos: "MF" },
    { name: "Tobias Moi", pos: "MF" }, { name: "Amin Cosic", pos: "FW" },
    { name: "Edvin Austbø", pos: "FW" }, { name: "Kelvin Frimpong", pos: "FW" },
    { name: "Nicholas D'Agostino", pos: "FW" }, { name: "Niklas Fuglestad", pos: "FW" },
    { name: "Peter Christiansen", pos: "FW" }, { name: "Romano Postema", pos: "FW" },
    { name: "Veton Berisha", pos: "FW" }, { name: "Zlatko Tripić", pos: "FW" },
  ],
  VIL: [
    { name: "Luiz Júnior", pos: "GK" }, { name: "Alex Freeman", pos: "DF" },
    { name: "Carlos Romero", pos: "DF" }, { name: "Juan Foyth", pos: "DF" },
    { name: "Logan Costa", pos: "DF" }, { name: "Pau Navarro", pos: "DF" },
    { name: "Renato Veiga", pos: "DF" }, { name: "Santiago Mouriño", pos: "DF" },
    { name: "Sergi Cardona", pos: "DF" }, { name: "Willy Kambwala", pos: "DF" },
    { name: "Alberto Moleiro", pos: "MF" }, { name: "Pape Gueye", pos: "MF" },
    { name: "Santi Comesaña", pos: "MF" }, { name: "Tajon Buchanan", pos: "MF" },
    { name: "Thiago Fernández", pos: "MF" }, { name: "Ayoze Pérez", pos: "FW" },
    { name: "Georges Mikautadze", pos: "FW" }, { name: "Gerard Moreno", pos: "FW" },
    { name: "Ilias Akhomach", pos: "FW" }, { name: "Nicolas Pépé", pos: "FW" },
    { name: "Pau Cabanes", pos: "FW" }, { name: "Tani Oluwaseyi", pos: "FW" },
  ],
};

module.exports = { teams, squads };
